name: Docker build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}" 

      - name: Build Docker image
        run: docker build -t jacarlint/app-map:${{ github.sha }} .

      - name: Tag Latest
        run: docker tag jacarlint/app-map:${{ github.sha }} jacarlint/app-map:latest

      - name: Push Docker image
        run: |
          docker push jacarlint/app-map:${{ github.sha }}
          docker push jacarlint/app-map:latest
